name: widget_spin
description: "Widget Spin is a package that makes rotation animation around a widget."
version: 1.0.4+1
homepage: https://github.com/hydev777/widget_spin
repository: https://github.com/hydev777/widget_spin

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  dart_code_linter: ^1.1.1
  dart_code_metrics: ^5.7.6
  very_good_analysis: ^5.1.0
  flutter_lints: ^5.0.0

flutter: